version: "3.7"

# if you are using firewalld add this consistent bridge name
# to your trusted zone
# sudo firewall-cmd --zone=trusted --add-interface=claircore --permanent
# sudo firewall-cmd --reload
networks:
  default:
    driver_opts:
      com.docker.network.bridge.name: distlock

services:

  postgres:
    image: postgres:11.5
    container_name: distlock-postgres
    environment:
      POSTGRES_USER: "distlock"
      POSTGRES_DB: "distlock"
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U distlock -d distlock" ]
      interval: 10s
      timeout: 9s
      retries: 3
      start_period: 10s
