---
name: CI

on: [push, pull_request]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    container: docker.io/library/golang:${{ matrix.go }}-buster
    strategy:
      matrix:
        go: ['1.15', '1.16']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dependencies
        run: apt-get update -y && apt-get install -y docker docker-compose
      - name: Tests
        run: go test -race -timeout 0 .

