---
name: CI

on: [push, pull_request]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    container: docker.io/library/golang:${{ matrix.go }}-buster
    strategy:
      matrix:
        go: ['1.13', '1.14']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Tests
        run: go test -v ./...
